name: Extrage Istoric 20 Zile
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Am trecut de la v3 la v4

      - name: Setup Python
        uses: actions/setup-python@v5 # Am trecut de la v4 la v5
        with:
          python-version: '3.11' # Versiune mai noua de Python

      - name: Install Libs
        run: pip install yfinance pandas

      - name: Run Extraction
        run: python istoric_20zile.py

      - name: Salveaza Rezultatul
        uses: actions/upload-artifact@v4 # Deja e v4, e ok, dar punem setarile corecte
        with:
          name: date-bursiere-20-zile
          path: date_extractie_20_zile.csv
